### ISSUE TITLE
Problems with the snapcraft package

### ISSUE THREAD

**Issue by kovzol** [kovzol/geogebra-discovery#4]
At https://snapcraft.io/geogebra-discovery there is an experimental snapcraft package available. Its source configuration file is https://github.com/kovzol/geogebra-discovery/blob/master/snapcraft.yaml. Unfortunately, some features do not work:
* When there is a folder with certain non-ASCII characters, an error message like
```commandline
Exception in thread "Basic L&F File Loading Thread" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/kovzol/K??pek
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:276)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:249)
	at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:300)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:289)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
  is reported on I/O operations. As a consequence, saving/loading files is somewhat uncomfortable, because no .ggb files are shown in the file system view. This seems to be present in newer OpenJDK versions as well (11 and 16 are both problematic). Maybe some languages like English are not affected.
* The 3D View does not work:
```commandline
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Caught handled GLException: X11GLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x532f7ca0, isOwner false, <7abbb159, 4977ecef>[count 0, qsz 0, owner <NULL>]]] on thread AWT-EventQueue-0-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:306)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.base/java.lang.Thread.run(Thread.java:831)
Caused[0] by GLException: AWT-EventQueue-0-SharedResourceRunner: Unable to create temp OpenGL context(1) on thread AWT-EventQueue-0-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:390)
    [1]: jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:770)
    [2]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:653)
    [3]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:591)
    [4]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:277)
    [5]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [6]: java.base/java.lang.Thread.run(Thread.java:831)
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Profile GL_DEFAULT is not available on null, but: []
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1012)
	at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:743)
	at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:754)
	at org.geogebra.desktop.geogebra3D.euclidian3D.opengl.RendererJogl.setDefaultProfile(RendererJogl.java:96)
	at org.geogebra.desktop.geogebra3D.euclidian3D.opengl.RendererCheckGLVersionD.<init>(RendererCheckGLVersionD.java:75)
	at org.geogebra.desktop.geogebra3D.euclidian3D.opengl.RendererCheckGLVersionD.<init>(RendererCheckGLVersionD.java:56)
	at org.geogebra.desktop.geogebra3D.euclidian3D.EuclidianView3DD.createRenderer(EuclidianView3DD.java:132)
	at org.geogebra.common.geogebra3D.euclidian3D.EuclidianView3D.start(EuclidianView3D.java:436)
	at org.geogebra.common.geogebra3D.euclidian3D.EuclidianView3D.<init>(EuclidianView3D.java:349)
	at org.geogebra.desktop.geogebra3D.euclidian3D.EuclidianView3DD.<init>(EuclidianView3DD.java:80)
	at org.geogebra.desktop.geogebra3D.App3D.getEuclidianView3D(App3D.java:492)
	at org.geogebra.desktop.geogebra3D.gui.layout.panels.EuclidianDockPanel3DD.getEuclidianView(EuclidianDockPanel3DD.java:47)
	at org.geogebra.desktop.gui.layout.panels.EuclidianDockPanelAbstract.loadComponent(EuclidianDockPanelAbstract.java:115)
	at org.geogebra.desktop.gui.layout.DockPanelD.updatePanel(DockPanelD.java:795)
	at org.geogebra.desktop.geogebra3D.gui.layout.panels.EuclidianDockPanel3DD.updatePanel(EuclidianDockPanel3DD.java:123)
	at org.geogebra.desktop.gui.layout.DockManagerD.show(DockManagerD.java:728)
	at org.geogebra.desktop.gui.layout.DockManagerD.show(DockManagerD.java:524)
	at org.geogebra.desktop.gui.GuiManagerD.setShowView(GuiManagerD.java:784)
	at org.geogebra.desktop.gui.GuiManagerD.setShowView(GuiManagerD.java:777)
	at org.geogebra.desktop.gui.menubar.ViewMenuApplicationD$ShowViewAction.actionPerformed(ViewMenuApplicationD.java:200)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

These issues occur only when the strict confinement is set. With the classic confinement they are not present. (But the classic confinement is no longer supported by Snapcraft for automated deployment.)

**Comment by kovzol** [comment]
The 3D View issue is fixed now: https://github.com/kovzol/geogebra-discovery/commit/8545f03ec2350073fe7578ae0fa1565c3e3dc8fb
A workaround for save/load: the user should click on the home button (house icon in the file manager), then one level up, and then navigate into the home folder again. The .ggb files are not shown, but loading after typing of their names (also file name expansion) works.

**Comment by kovzol** [comment]
https://github.com/kovzol/geogebra-discovery/commit/185b6341b5bac07e42876350b03efec910c81dc2 fixes the save/load problem.
The remaining issue is to save preferences on exit. But this is a very minor one and it can be ignored.

**Comment by kovzol** [comment]
https://github.com/kovzol/geogebra-discovery/commit/e3d35f1aff3489defbe9088043350cc4ae376025 and https://github.com/kovzol/geogebra-discovery/commit/d92cf9a15ababc2e608296dfad856b712fd2c57b fix the issue with the preferences.
